global:
  modules:
    kafka:
      enabled: true
    zookeeper:
      enabled: true
    ## Should not be enabled if external is set to true	
    kafkaClient:
      enabled: false
      
kafka:
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    size: "1Gi"