dependencies:
- name: kafka
  version: 0.4.2
  repository: "file://charts/kafka"

- name: kafkaClient
  version: 0.0.0
  repository: "file://charts/kafka-client"
  condition: global.modules.kafkaClient.enabled
