dependencies:
- name: kafka
  version: 0.4.2
  repository: "file://charts/kafka"
- name: zookeeper
  version: 0.6.1
  repository: "file://charts/zookeeper"
- name: kafka-manager
  version: 1.0.0
  repository: "file://charts/kafka-manager"
- name: kafka-monitor
  version: 0.0.1
  repository: "file://charts/kafka-monitor"
- name: kafkaClient
  version: 0.0.0
  repository: "file://charts/kafka-client"
  condition: kafkaClient.enabled
