dependencies:
- name: kafka
  version: 0.4.2
  repository: "file://charts/kafka"
  condition: kafka.enabled
- name: zookeeper
  version: 0.6.1
  repository: "file://charts/zookeeper"
  condition: zookeeper.enabled
- name: kafka-manager
  version: 1.0.0
  repository: "file://charts/kafka-manager"
  condition: kafka-manager.enabled
- name: kafka-monitor
  version: 0.0.1
  repository: "file://charts/kafka-monitor"
  condition: kafka-monitor.enabled
- name: kafkaClient
  version: 0.0.0
  repository: "file://charts/kafka-client"
  condition: kafkaClient.enabled
