apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: {{ .Release.Namespace }}
spec:
  containers:
  - name: kafka
    image: {{ .Values.image }}:{{ .Values.imageTag }}
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
